#  Yaml CI config for Gitlab See. http://docs.gitlab.com/ce/ci/yaml/README.html
#  Machine image on which to build, test etc
image: docker-registry.oxfordnanolabs.local:5000/ont-base-ofan-dev:14.04

variables:
  REPO_DEVELOPMENT: "trusty-unstable"
  REPO_STAGING:     "trusty-testing"
  REPO_PRODUCTION:  "trusty-stable"
  PATCH:            $CI_BUILD_ID

stages:
  - test
  - publish

testing:
  stage: test
  script:
      - apt-get update
      - make deps
      - make deb
  except:
      #  Don't test tags (just branches)
      - tags
  artifacts:
    paths:
      - ./*.deb

upload-development:
  stage: publish
  script:
    - echo "$SSH_PRIVATE_KEY" > .privkey
    - chmod 600 .privkey
    - scp -o StrictHostKeyChecking=no -i .privkey *.deb hudson@deb-repo.oxfordnanolabs.local:/var/www/apt/$REPO/
  variables:
    REPO: $REPO_STAGING
  only:
    - dev

upload-staging:
  stage: publish
  script:
    - echo "$SSH_PRIVATE_KEY" > .privkey
    - chmod 600 .privkey
    - scp -o StrictHostKeyChecking=no -i .privkey *.deb hudson@deb-repo.oxfordnanolabs.local:/var/www/apt/$REPO/
  variables:
    REPO: $REPO_STAGING
  only:
    - master

upload-prod:
  stage: publish
  script:
    - echo "$SSH_PRIVATE_KEY" > .privkey
    - chmod 600 .privkey
    - scp -o StrictHostKeyChecking=no -i .privkey *.deb hudson@deb-repo.oxfordnanolabs.local:/var/www/apt/$REPO/
  variables:
    REPO: $REPO_PRODUCTION
  only:
    - /^release-\d+\.\d+(?:.\d+)?(?:-\d+)?$/ # use regexp
